# Basic Python

## 1. Split this string

In [61]:
s = "Hi there Kishore!"


In [62]:
s = "Hi there Kishore!"
print(s.split())

['Hi', 'there', 'Kishore!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [63]:
planet = "Earth"
diameter = 12742

In [64]:
planet = "Earth"
diameter = 12742
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [65]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [66]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [67]:
import numpy as np
ar=np.zeros(10)
print(ar)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [68]:
import numpy as np
ar1=np.ones(10)*5
print(ar1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [69]:
import numpy as np
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [70]:
a=np.arange(0,9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b), axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [72]:
import pandas as pd
a=[[1,2],[3,4],[4,5]]
d = pd.DataFrame(a,columns=["column1","column2"])
print(d)

   column1  column2
0        1        2
1        3        4
2        4        5


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [73]:
dates = pd.date_range(start ='1-1-2023', end ='10-02-2023')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [74]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [75]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
d = pd.DataFrame(lists,columns=["column1","column2","column3"])
print(d)

   column1 column2  column3
0        1     aaa       22
1        2     bbb       25
2        3     ccc       24
